### ISSUE TITLE
Обсуждение, как хранить данные

### ISSUE THREAD

**Issue by alexbaumgertner** [gorod-mechty/gorod-mechty#3]
Предлагаю все данные хранить в `/content`:
- `/content/pages/` – страницы, например `/pages/about.json`
- `/content/projects` – проекты

и тд.

**Comment by alexbaumgertner** [comment]
Разумеется, пока можно все положить в bemjson

**Comment by vithar** [comment]
Данные разных страниц хранятся по разному, я описал в ТЗ:
https://github.com/gorod-mechty/gorod-mechty/wiki/tz

Как хранить projects и cashflow решим позже, сейчас надо сделать первую минимальную версию (см. почту).

**Comment by alexbaumgertner** [comment]
:ok:
