### ISSUE TITLE
Проблема с рендером блока content

### ISSUE THREAD

**Issue by basilred** [gorod-mechty/gorod-mechty#7]
Почему-то `gulp` перестал рендерить `content` для страниц. Не могу разобраться в чем проблема, и откуда появилась.
Ребята, проверьте у себя, пожалуйста. Может быть я как-то локально конфигурацию сломал или пакет какой-то.
Это прям если склонировать и, ничего не изменяя, запускать.
![screen shot 2016-02-11 at 20 16 17](https://cloud.githubusercontent.com/assets/413033/12984146/875b283a-d0fd-11e5-826b-0cd8a67ce5a4.png)

**Comment by vithar** [comment]
�������� �� ��������.

**Comment by tadatuta** [comment]
@vithar ответ из почты не засчитан ;)

**Comment by vithar** [comment]
Посмотрю на выходных.

**Comment by basilred** [comment]
@vithar спасибо.

**Comment by vithar** [comment]
Fixed in https://github.com/gorod-mechty/gorod-mechty/commit/8d827f98fe99a4bde7024658be3600f151c7b1d6
